WebPage/Models/ErrorViewModel.cs
using System;

namespace WebPage.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebPage/Models/UserRegistration.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebPage.Models
{
    public class UserRegistration
    {
        [Key]
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

WebPage/Models/WebFrom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebPage.Models
{
    public class WebFrom
    {
        [Key]
        public int Id { get; set; }
        [Required (ErrorMessage ="* Date can t black")]
        public DateTime Date { get; set; }
        [Required(ErrorMessage = "* Name can t black")]
        public string Name { get; set; }
        [Required(ErrorMessage = "* Email can t black")]
        public string Email { get; set; }
        [Required(ErrorMessage = "* Mobile can t black")]
        public long Mobile { get; set; }
        [Required(ErrorMessage = "* Salary can t black")]
        public Decimal Salary { get; set; }
        [Required(ErrorMessage = "* Location can t black")]
        public string Location { get; set; }
        [Required(ErrorMessage = "* Department can t black")]
        public string Department { get; set; }

    }
}

WebPage/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebPage.Models;

namespace WebPage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebPage/Controllers/WebPageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebPage.DataContexts;
using WebPage.Models;

namespace WebPage.Controllers
{
    public class WebPageController : Controller
    {
        private readonly ApplicationContect context;
        public WebPageController(ApplicationContect context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var result = context.webFroms.ToList();


            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(WebFrom model)
        {
            if (ModelState.IsValid) 
            {
                var rest = new WebFrom()
                {
                    Date = model.Date,
                    Name = model.Name,
                    Email=model.Email,
                    Mobile=model.Mobile,
                    Salary=model.Salary,
                    Location=model.Location,
                    Department=model.Department,
                };
                context.webFroms.Add(rest);
                context.SaveChanges();
                TempData["error"] = "Record Savedl";
                return RedirectToAction("Index");
            }
           else
            {
                TempData["massege"] = "Empty field can't  Submit";
                return View(model);
            }
        }
        public IActionResult Delete(int Id,WebFrom pro)
        {
            var rest = context.webFroms.SingleOrDefault(m => m.Id == Id);
            context.webFroms.Remove(rest);
            context.SaveChanges();
            TempData["error"] = "Record Deleted";
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int Id)
        {
            var res = context.webFroms.SingleOrDefault(m => m.Id == Id);
            var result = new WebFrom()
            {
               Date =res.Date ,
               Name=res.Name,
               Email=res.Email,
               Mobile=res.Mobile,
               Salary=res.Salary,
               Location=res.Location,
               Department=res.Department,
            };


            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(WebFrom model)
        {
            var rest = new WebFrom()
            {
                Id=model.Id,
              Date=model.Date,
              Name=model.Name,
              Email=model.Email,
              Mobile=model.Mobile,
              Salary=model.Salary,
              Location=model.Location,
              Department=model.Department,
            };
            context.webFroms.Update(rest);
            context.SaveChanges();
            TempData["errorM"] = "Record Edit";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(UserRegistration model)
        {
            var rest = new UserRegistration()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                Password=model.Password,
                ConfirmPassword=model.ConfirmPassword,       
        };
            context.UserRegistrations.Add(rest);
            context.SaveChanges();
            TempData["errorM"] = "Record Edit";
            return RedirectToAction("Index");
           
        }
    }
}

WebPage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebPage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebPage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WebPage" asp-action="Index">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WebPage" asp-action="Index">Location</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebPage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebPage/Views/WebPage/Create.cshtml
@model WebPage.Models.WebFrom

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-7 offset-3">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-primary">Add New</h1>
                    <p class="text-center text-danger">@TempData["massege"]</p>
                </div>
                <div class="card-body">
                    <form method="post" asp-action="Create">
                        
                            <label asp-for="Date"></label>
                            <div class="card-body">
                                <div class="form-group mb-0 input-block" data-toggle="tooltip" data-placement="top" title="Delivery Date">
                                    @Html.TextBoxFor(x => x.Date, new
                                    {
                                        @id = "Date",
                                        @type = "date",
                                      @value = DateTime.Now.ToShortDateString()
                                    })
                                </div>
                            </div>

                            <span asp-validation-for="Date" class="text-danger"></span>
                       

                        <div class="form-group">
                            <label asp-for="Name"></label>
                            <input type="text" asp-for="Name" class="form-control" placeholder="Enter Name" />
                            <span asp-validation-for="Name" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <label asp-for="Email"></label>
                            <input type="text" asp-for="Email" class="form-control" placeholder="Enter Email" />
                            <span asp-validation-for="Email" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <label asp-for="Mobile"></label>
                            <input type="text" asp-for="Mobile" class="form-control" placeholder="Enter Mobile" />
                            <span asp-validation-for="Mobile" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <label asp-for="Salary"></label>
                            <input type="text" asp-for="Salary" class="form-control" placeholder="Enter Salary" />
                            <span asp-validation-for="Salary" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <label asp-for="Location"></label>
                            <input type="text" asp-for="Location" class="form-control" placeholder="Enter Location" />
                            <span asp-validation-for="Location" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <label asp-for="Department"></label>
                            <input type="text" asp-for="Department" class="form-control" placeholder="Enter Department" />
                            <span asp-validation-for="Department" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <input typeof="button" class="btn btn-primary btnSubmit" type="submit" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebPage/Views/WebPage/Edit.cshtml
@model WebPage.Models.WebFrom


@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="row">
        <div class="col-7 offset-3">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-danger">Edit New</h1>
                </div>
                <div class="card-body">
                    <form method="post" asp-action="Edit">
                        <div class="form-group">
                            <label asp-for="Date"></label>
                            <input type="hidden" asp-for="Id" />
                            <input type="text" asp-for="Date" class="form-control" placeholder="Enter Date" />
                        </div>
                        @*<div class="col-sm-6 col-lg-4 mt-2 mt-sm-3" data-toggle="tooltip" data-placement="top" title="Date From">
                                <div class="form-group mb-0 input-block">
                                    @(Html.Kendo().DatePicker().Name("DateFrom").Format("dd-MMM-yyyy").HtmlAttributes(new { style = "width: 100%", id = "DateFrom" }))
                                </div>
                            </div>*@
                        <div class="form-group">
                            <label asp-for="Name"></label>
                            <input type="text" asp-for="Name" class="form-control" placeholder="Enter Name" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Email"></label>
                            <input type="text" asp-for="Email" class="form-control" placeholder="Enter Email" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Mobile"></label>
                            <input type="text" asp-for="Mobile" class="form-control" placeholder="Enter Mobile" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Salary"></label>
                            <input type="text" asp-for="Salary" class="form-control" placeholder="Enter Salary" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Location"></label>
                            <input type="text" asp-for="Location" class="form-control" placeholder="Enter Location" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Department"></label>
                            <input type="text" asp-for="Department" class="form-control" placeholder="Enter Department" />
                        </div>
                        @*<div class="form-row">
                                <div class="col-md-12 mb-1">
                                    <button class="btn btn-primary btnSubmit" type="submit">Submit</button>
                                </div>
                            </div>*@
                        <div class="form-group">
                            <input typeof="button" class="btn btn-primary btnSubmit" type="submit" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebPage/Views/WebPage/Index.cshtml
@model IEnumerable<WebPage.Models.WebFrom>
@{
    ViewData["Title"] = "Index";
}

<div class=" container">

    <div class="row">
        <div class="col-8 offset-2">
            <h1 class="text-center text-primary"> Application Record </h1>
            <table class="table table-bordered">

                <a class="btn btn-sm btn-success" asp-controller="WebPage" asp-action="Create">Create</a>

                <p class="text-center text-success">@TempData["error"]</p>
                <tr class="text-center">
                    <th>Id</th>
                    <th>date</th>>
                    <th>Name</th>
                    <th>Mobile</th>
                    <th>Salary</th>
                    <th>Location</th>
                    <th>Department</th>
                    <th>Edit</th>
                    <th>Action</th>
                </tr>
                @foreach (var Data in Model)
                {
                    <tr class="text-center">
                        <td>@Data.Id</td>
                        <td>@Data.Date</td>
                        <td>@Data.Name</td>
                        <td>@Data.Mobile</td>
                        <td>@Data.Salary</td>
                        <td>@Data.Location</td>
                        <td>@Data.Department</td>
                        <td>
                            <a class="btn btn-sm btn-warning" asp-controller="WebPage" asp-action="Edit" asp-route-id="@Data.Id">Edit</a>
                        </td>
                        <td>
                            <a class="btn btn-sm btn-danger" asp-controller="WebPage" asp-action="Delete" asp-route-id="@Data.Id">Delete</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

WebPage/Views/WebPage/Register.cshtml
@model WebPage.Models.UserRegistration
<h1>Register</h1>

<hr />
div class="container">
<div class="row">
    <div class="col-7 offset-3">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-sm btn-success" asp-controller="WebPage" asp-action="Register">Register New</a>

                <p class="text-center text-danger">@TempData["massege"]</p>
            </div>
            <div class="card-body">
                ]      
                    <div class="row">
                        <div class="col-md-4">
                            <form method="post" asp-action="Register">
                                <div asp-validation-summary="All" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="FirstName" class="control-label"></label>
                                    <input asp-for="FirstName" class="form-control" />
                                    <span asp-validation-for="FirstName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="LastName" class="control-label"></label>
                                    <input asp-for="LastName" class="form-control" />
                                    <span asp-validation-for="LastName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Email" class="control-label"></label>
                                    <input asp-for="Email" class="form-control" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Password" class="control-label"></label>
                                    <input asp-for="Password" class="form-control" />
                                    <span asp-validation-for="Password" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ConfirmPassword" class="control-label"></label>
                                    <input asp-for="ConfirmPassword" class="form-control" />
                                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Register" class="btn btn-primary" />
                                </div>
                            </form>
                        </div>
                    </div>                  
            </div>
        </div>
    </div>
</div>
    